version: '3'
services:

  wordpress:
    image: shellyln/go-single-bin-static-web-server:latest
    container_name: myhttpd
    restart: always
    ports:
      - 8080:8080
    environment:
      PORT: 8080
